[tool.poetry]
name = "spotter"
version = "0.0.1"
description = "Stellar contamination estimates from rotational light curves"
authors = ["Lionel Garcia", "Benjamin Rackham"]
license = "MIT"
readme = "readme.md"

[tool.poetry.dependencies]
numpy = "*"
healpy = "*"
matplotlib = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"
black = "*"

[tool.poetry.group.docs.dependencies]
sphinx = "*"
docutils = "*"
jupyterlab = "*"
myst-parser = "*"
sphinx-book-theme = "^1.0.0"
myst-nb = "*"
sphinx-copybutton = "*"
sphinx-design = "*"
toml = "*"
ipywidgets = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
